### PR TITLE
Add member Rijrya

### PR DESCRIPTION
**Pull request by richardyzhu**
i forgot to do this 4 motnshs ago. i have done it now 
i also deleted a new line oosp

### CODE REVIEW

**Comment by Wayakuyee** [comment]
:rijrya:

**Comment by prts44** [comment]
:rijrya:

**Comment by solstice23** [comment]
:rijrya:

**Comment by danielq987** [comment]
Closing because we have since moved where members data is located. rijrya content has been added in https://github.com/osu-uwaterloo/osu-uwaterloo-website/pull/25

**Pull request closed without merging**
