### PR TITLE
Add personal website and Github to members page

### PR DESCRIPTION
**Pull request by solstice23**
+ Refactor members page
+ Add personal website and Github to members page
+ Sort members by their names (except executives)

### CODE REVIEW

**Review by yfxu — COMMENTED** [review]
ok this code makes our lives 90000 times easier what a good PR XD

Before I merge tho, how do you feel about using the `member-entry` partial for each type of member (exec, member, alum)? It's not a super big deal but I guess with the proposed changes, I can be a regular member but then give myself a `role` attribute when I shouldn't have one, and it'd actually get displayed on the website.

I really like the changes to show sorted members, new links, etc tho :D

**Comment by solstice23** [comment]
Because the member list is preconfigured, not user-input, we can simply avoid adding the `role` field to non-executive members. However if you want it never appears in the non-executive members, I can add an extra check in the code. But it seems to be unnecessary.

**Comment by yfxu** [comment]
> Because the member list is preconfigured, not user-input, we can simply avoid adding the `role` field to non-executive members

It's true that we can just make sure we never add invalid attributes at PR review-time, but we can't really predict the future. There may be a time when we start automating more of the member-addition process, at which point there may be new possible sources of error. I know it's a lot of work, and I appreciate what you've done so far, but I think it'd great if we added the checks in place early on ;'D

**Review by danielq987 — APPROVED** [review]
did a quick skim looks fine to me

**Pull request merged**
